### PR TITLE
Just adding the skeleton for the frontend code... More changes and refinements will be added later  

### PR DESCRIPTION
**Pull request by ghost**
Btw, anyone involved is free to examine the directory structure and place the needed changes :)

### CODE REVIEW

**Comment by RichieMuga** [comment]
The code is in nextjs and react is the framework we'll be using

**Comment by ghost** [comment]
Oops.. my bad. So, we use the Create React App? @RichieMuga

**Comment by ghost** [comment]
Reconfigured the initial codebase for the front end with React Vite. Lemme know if all is as wanted...

**Comment by RichieMuga** [comment]
The problem is the github workflows you've created. The CI checks have failed on your side and also the steps are not checking for the react they are checking for the node in which they have failed. Kindly remove the workflow you've created from your branch and create another branch then push.

**Comment by Manu254rce** [comment]
Ooh... But I think I can still push with the same branch but a different pull request. Therefore, all I need is to simply remove the workflow. As for Cite and React, that still stands, right?

**Pull request merged**
